version: '3'
services:
  front-end:
    container_name: frontend
    restart: always
    build: sistema_contable/
    ports:
      - '8080:3000'
  server-app:
    container_name: backend
    restart: always
    build: web_api/webapi/
    command: npm run start
    ports:
      - '3001:3001'
    links:
      - mongo
      #- redis
    #environment:
      #- REDIS_URL=redis: //cache
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  #redis:
   # container_name: cache
   # image: redis
   # expose:
   #   - 6379
  